prompt = 'run:  '
padding = 100
fonts = [
    'Fira Code',
]
font_size = 32.0
[history]
decrease_interval = 48
[colors]
background = '#1e1e2ec8'
prompt = '#6c7086ff'
text = '#cdd6f4ff'
text_query = '#f38ba8ff'
text_selected = '#f38ba8ff'
[keybindings]
paste = ["ctrl+v"]
execute = ["KP_Enter", "Return"]
delete = ["KP_Delete", "Delete", "BackSpace"]
delete_word = ["ctrl+KP_Delete", "ctrl+Delete", "ctrl+BackSpace"]
complete = ["Tab"]
nav_up = ["Up"]
nav_down = ["Down"]
exit = ["Escape"]
